version: "3.9"

services:
  polypress:
    image: polypress:release_0.7.0
    build:
      context: .
      dockerfile: ./.docker/development/Dockerfile
<<<<<<< Updated upstream
=======
      args:
        RUBY_VERSION: "2.7.2"
        BUNDLER_VERSION_OVERRIDE: "2.2.14"
>>>>>>> Stashed changes
    ports:
      - "3000:3000"
    volumes:
      - .:/polypress:cached
      - rails_cache:/polypress/tmp/cache
      - bundle:/bundle
      - node_modules:/polypress/node_modules
      - packs:/polypress/public/packs
    env_file:
      - ./.env
    environment:
      BLIND_INDEX_MASTER_KEY: ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
      # INTERFACE: "0.0.0.0"
      RABBITMQ_HOST: amqp://rabbitmq
      RABBITMQ_VHOST: event_source
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-guest}
      RABBITMQ_PORT: ${RABBITMQ_PORT:-5672}
      RABBITMQ_URL_EVENT_SOURCE: ${RABBITMQ_URL_EVENT_SOURCE:-amqp://guest:guest@amqp:5672}
      RABBITMQ_USERNAME: ${AMQP_USERNAME:-guest}
      RAILS_ENV: ${RAILS_ENV:-development}
    tmpfs:
      - /tmp
    command: bash -c "rm -f tmp/pids/server.pid && mkdir -p tmp/pids && yarn install --check-files && bundle install && bundle exec puma -C config/puma.rb"
    depends_on:
      - mongodb
      - rabbitmq

  mongodb:
    image: mongo:4.2
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: polypress_rabbitmq
    volumes:
      - rabbitmq_etc:/etc/rabbitmq/
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_logs:/var/log/rabbitmq/
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE:-123456789}
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS:-guest}
    ports:
      - 4369
      - 5672:5672
      - 25672:25672
      - 15672:15672

volumes:
  bundle:
  rails_cache:
  node_modules:
  packs:
  mongodb:
  mongodb_config:
  rabbitmq_etc:
  rabbitmq_data:
  rabbitmq_logs:
