---
registry:
  - namespace:
      - :features
    features:
      - key: :pre_audit_report
        is_enabled: true
        settings:
          - key: :carrier_hios_ids
            item: ["96667", "48396", "33653", "50165", "54879"]