---
registry:
  - namespace:
      - :features
    features:
      - key: :pre_audit_report
        is_enabled: true
        settings:
          - key: :carrier_hios_ids
            item: ["48396", "50165", "33653", "96667"]