name: full check suite
on:
  push:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - name: Cache Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: v1-${{ runner.os }}-polypress-gems-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('**/Gemfile' ) }}
          restore-keys: |
            v1-${{ runner.os }}-polypress-gems-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('**/Gemfile' ) }}
      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle check || bundle install
      - name: Run rubocop
        run: bundle exec rubocop-git origin/trunk
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: getong/rabbitmq-action@v1.2
        with:
          rabbitmq version: "3.8.2-management-alpine"
          host port: 5672
          rabbitmq user: "guest"
          rabbitmq password: "guest"
          rabbitmq vhost: "/"
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
      - uses: wbari/start-mongoDB@v0.2
        with:
          mongoDBVersion: "3.6"
      - name: Cache Gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: v1-${{ runner.os }}-polypress-gems-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('**/Gemfile' ) }}
          restore-keys: |
            v1-${{ runner.os }}-polypress-gems-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('**/Gemfile' ) }}
      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle check || bundle install
      - name: Run rspec
        run: bundle exec rspec
